### PR TITLE
Netlify Haxx

### PR DESCRIPTION
**Pull request by Johnmiicheal**
Just merge both together so the code base should be the same, then it can deploy the current code

### CODE REVIEW

**Comment by owolabioromidayo** [comment]
No way in hell. That's atrocious. I found the real issue. no react-liquid-gauge. I checked the deploy logs.

**Comment by Johnmiicheal** [comment]
> No way in hell. That's atrocious. They're too far apart now to merge. I found the real issue. no react-liquid-gauge. I checked the deploy logs.

Okay, cool

**Comment by owolabioromidayo** [comment]
Loll didnt see this message. Just thought it would be fun to be angry.

**Comment by Johnmiicheal** [comment]
Well it wasn't. I felt stupid... I don't like feeling stupid @owolabioromidayo

**Pull request closed without merging**
